// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk1QAh0VBQFdkIoCBNXdUu_HaSigidsGE',
    appId: '1:1053476714473:web:4c6c7784b880fa7af07d78',
    messagingSenderId: '1053476714473',
    projectId: 'dtpro-9b908',
    authDomain: 'dtpro-9b908.firebaseapp.com',
    databaseURL: 'https://dtpro-9b908-default-rtdb.firebaseio.com',
    storageBucket: 'dtpro-9b908.appspot.com',
    measurementId: 'G-ECE2PNBRPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc2lflt-hxc8Y_EijTnjHtB3VYbN1JfxQ',
    appId: '1:1053476714473:android:fa6948ef0daeb975f07d78',
    messagingSenderId: '1053476714473',
    projectId: 'dtpro-9b908',
    databaseURL: 'https://dtpro-9b908-default-rtdb.firebaseio.com',
    storageBucket: 'dtpro-9b908.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS2C3VXVB21EstFI-UfIZh_eNNjx2vV6s',
    appId: '1:1053476714473:ios:9335173bc60aa2fef07d78',
    messagingSenderId: '1053476714473',
    projectId: 'dtpro-9b908',
    databaseURL: 'https://dtpro-9b908-default-rtdb.firebaseio.com',
    storageBucket: 'dtpro-9b908.appspot.com',
    iosClientId: '1053476714473-o9dugc2oubcou3ovdcufntksq9suqdgt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS2C3VXVB21EstFI-UfIZh_eNNjx2vV6s',
    appId: '1:1053476714473:ios:9335173bc60aa2fef07d78',
    messagingSenderId: '1053476714473',
    projectId: 'dtpro-9b908',
    databaseURL: 'https://dtpro-9b908-default-rtdb.firebaseio.com',
    storageBucket: 'dtpro-9b908.appspot.com',
    iosClientId: '1053476714473-o9dugc2oubcou3ovdcufntksq9suqdgt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk1QAh0VBQFdkIoCBNXdUu_HaSigidsGE',
    appId: '1:1053476714473:web:78bf4a696ab927bff07d78',
    messagingSenderId: '1053476714473',
    projectId: 'dtpro-9b908',
    authDomain: 'dtpro-9b908.firebaseapp.com',
    databaseURL: 'https://dtpro-9b908-default-rtdb.firebaseio.com',
    storageBucket: 'dtpro-9b908.appspot.com',
    measurementId: 'G-WQMFYKSN4T',
  );
}
